# Site wide configuration

title:            Mike Schaekermann
locale:           en
url:              http://127.0.0.1:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll/scholar

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Mike Schaekermann
  avatar: mike-schaekermann-photo-1.jpg
  bio: University of Waterloo Computer Science Ph.D. candidate with a degree in Medicine
  email: mikeschaekermann@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-41409977-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mikeschaekermann
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: mike-schäkermann-058abb75
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

# Bibliography
scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  group_by: none
  group_order: ascending
  source: _bibliography
  bibliography: papers.bib
  bibliography_template: bibliography
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: true
  #details_dir:    bibliography
  #details_layout: bibtex.html
  details_link:   Details
  repository: publications

  query: "@*"

include: [".htaccess"]
exclude: ["tasks", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
